# Generated by Django 4.2.20 on 2025-03-25 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dream', '0004_alter_dreamimage_position'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name', 'tag_type')},
        ),
        migrations.RemoveField(
            model_name='tag',
            name='created_by',
        ),
    ]
