# Generated by Django 4.2.20 on 2025-03-19 05:15

from django.db import migrations


def init_categories(apps, schema_editor):
    DreamCategory = apps.get_model('dream', 'DreamCategory')
    categories = [
        'normal',
        'memorable',
        'indicate',
        'archetypal',
        'lucid',
        'nightmare',
        'repeating',
        'sleep_paralysis'
    ]

    for category in categories:
        DreamCategory.objects.get_or_create(name=category)


def reverse_init(apps, schema_editor):
    DreamCategory = apps.get_model('dream', 'DreamCategory')
    DreamCategory.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('dream', '0002_dream_dreamcategory_alter_user_phone_number_and_more'),
    ]

    operations = [
        migrations.RunPython(init_categories, reverse_init),
    ]
