# Generated by Django 4.2.20 on 2025-03-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream', '0003_init_dream_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dreamimage',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='图片在梦境内容的位置'),
        ),
    ]
