# Generated by Django 4.2.20 on 2025-06-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream', '0007_alter_user_email_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_method',
            field=models.CharField(choices=[('email', '邮箱'), ('phone', '手机')], default='email', max_length=10, verbose_name='注册方式'),
        ),
    ]
