# Generated by Django 4.2.20 on 2025-07-04 06:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream', '0008_user_registration_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True, verbose_name='邮箱地址'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator('^1[3-9]\\d{9}$', '请输入正确的手机号')], verbose_name='手机号'),
        ),
    ]
